apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.container.name }}
        image: {{ .Values.deployment.container.image }}
        ports:
        - containerPort: {{ .Values.deployment.container.port }}
      healthCheck:
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.deployment.container.port }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.deployment.container.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
      resources:
        {{- toYaml .Values.deployment.resources | nindent 8 }}
---
